apiVersion: v1
kind: Service
metadata:
  name: service-container-back
  namespace: container-development
spec:
  selector:
    app: container-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP